name: Scala CI

on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        java: [8, 21]
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - uses: actions/checkout@v5
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: ${{matrix.java}}
        distribution: 'adopt'
    - uses: sbt/setup-sbt@v1
    - name: Run tests
      run: sbt scalafmtSbtCheck "+ scalafmtCheckAll" +test
